version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visa_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: visa_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    image: java-app-image
    container_name: java-app-container
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/visa_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: securepass
    ports:
      - "7000:7000"
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network: