{
 "title": "app services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database Pod",
   "type": "gauge",
   "description": "panel to display if the database pod is up",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=\"app\", pod=\"database-app-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress-Controller Pod",
   "type": "gauge",
   "description": "panel to display if the ingress controller pod is up",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=\"ingress-nginx\", pod=~\"ingress-nginx-controller-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Front_end Pods",
   "type": "gauge",
   "description": "panel to display if the front-end pods are up",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=\"app\", pod=~\"react-app-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Back_end Pods",
   "type": "gauge",
   "description": "panel to display if the Back-end pods are up",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=\"app\", pod=~\"java-app-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}