apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cron-job
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mustaqmstk/Visa-Holder-Movement-Tracker.git
    targetRevision: main
    path: devops/kubernetes/gitops/manifests/cron-job
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true